### PR TITLE
Merge Jetpack Compose 1.4.3

### PR DESCRIPTION
**Pull request by igordmn**
1. Revert commits between the base(1.4.0, 1.4.3) and 1.4.0:

jetpack-1.4.0 - [c5b142d6ab0494c996b2378d5008ac1cd6da75f3 ](https://developer.android.com/jetpack/androidx/releases/compose-animation#1.4.0)
jetpack-1.4.3 - [0872f930da585f7fbf6e17c74b1dc42045e8b2c6](https://developer.android.com/jetpack/androidx/releases/compose-animation#1.4.3)
igor.demin/revert-1.4.0-1.4.3 - a temporary branch, where we revert commits that exists in 1.4.0, but doesn't exist in 1.4.3
igor.demin/merge-1.4.3 - this PR branch, initially points to jb-main

```
git checkout -b igor.demin/revert-1.4.0-1.4.3
git merge-base jetpack-1.4.0 jetpack-1.4.3 # 6022301db806601f282c53b8cbb5a981923a1589 - the last commit that exists in 1.4.0 and in 1.4.3
git reset --hard 6022301db806601f282c53b8cbb5a981923a1589

git merge jetpack-1.4.0 --no-ff # merge the commits again, because we have them in jb-main and we would like to automatically solve the conflicts
git revert HEAD -m 1 # revert the merge commit, and exclude all commits that exists only in 1.4.0

git checkout igor.demin/merge-1.4.3
git merge jetpack-1.4.0-release-commits-reverted
```

2. Merge the 1.4.3 commit
```
git merge jetpack-1.4.3
```

3. Ignore failing Compose Runtime tests. See https://github.com/JetBrains/compose-multiplatform/issues/3211

### CODE REVIEW

**Comment by igordmn** [comment]
I will push this branch directly into `jb-main` after the review, to preserve the commits.

**Comment by igordmn** [comment]
P.S. there is an option to enable this via GitHub, but we need to discuss consequences 

image

**Review by MatkovIvan — APPROVED** [review]

**Review by MatkovIvan — APPROVED** [review]

**Review by MatkovIvan — COMMENTED** [review]
Wait. Why it doesn't contain https://android-review.googlesource.com/c/platform/frameworks/support/+/2475171 ?

**Comment by igordmn** [comment]
Merged into jb-main

image

**Pull request closed without merging**
