### PR TITLE
UIKit SnapshotManager Dispatchers.Main

### PR DESCRIPTION
**Pull request by dima-avdeev-jb**
It fixes this bug: https://github.com/JetBrains/compose-multiplatform/issues/2845

### CODE REVIEW

**Comment by igordmn** [comment]
About the context. Compose Runtime has bugs when this is not an UI thread, so we revert it for now, to avoid them.

@dima-avdeev-jb, by the way, the crash in the issue doesn't look as a bug in Compose Runtime, but as a bug of our implementation of threads for Kotlin Native. Let's not close it, until we figure out what is the real issue.

Even if we fixed it for our case, this crash can still happen for other cases, when the application has some work in a background thread, and access `mutableStateOf`/`derivedStateOf`.

**Review by igordmn — APPROVED** [review]

**Comment by eymar** [comment]
@dima-avdeev-jb do the tests in ui, foundation pass with this change? (In skikoTest sourceset).
They used to get stuck when I tried Main dispatcher or SkikoMainUiDispatcher. 

I'm wondering if our own single threaded (non ui) dispatcher would still fix the bug you encountered and the issue with the tests.

**Comment by dima-avdeev-jb** [comment]
Tests stucks.
newSingleThreadContext don't fixes crash.

**Comment by eymar** [comment]
In this case, it seems to be a probelm in tests that they timeout (60s). 
So I think we can merge this PR and deal with the tests separately.

**Review by eymar — APPROVED** [review]

**Pull request merged**
