### PR TITLE
Magnifier for iOS 17+

### LINKED ISSUE #3692: Commonize Modifier.magnifier
See https://github.com/androidx/androidx/blob/41cb7d5c422180edd89efde4076f9dc724d3a313/compose/foundation/foundation/src/androidMain/kotlin/androidx/compose/foundation/Magnifier.kt#L94

It's API is applicable to `commonMain`, but it is in `androidMain`

Magnifier is usual useful during text selection

### PR DESCRIPTION
**Pull request by alexzhirkevich**
## Proposed Changes

- Magnifier for iOS 17+
- Modifier.magnifier in common

## Testing

Test: try magnifier in all types of text fields

## Issues Fixed

Fixes: https://github.com/JetBrains/compose-multiplatform/issues/3692

### CODE REVIEW

**Comment by mazunin-v-jb** [comment]
Hello! Thank you for the request.
I'll look thoroughly into it on weekend.
And we need one more person to review, I'll ask someone from our team.

**Comment by alexzhirkevich** [comment]
I'd wait for https://github.com/JetBrains/compose-multiplatform-core/pull/980. It contains stable magnifier definition that is slightly different from current

**Comment by mazunin-v-jb** [comment]
Hello, @alexzhirkevich!
We discussed this change with Google, the general idea is good, but it needs to be iterated a bit on their side.
The changes in commonMain should be done in AOSP first. We avoid changing commonMain API here without changing it in AOSP first without a good reason. 
So, could you please create a CL (Change List, PR) in AOSP project first?

Just in case, here is some useful information:
1. How to clone AOSP:
```
mkdir ~/bin
PATH=~/bin:$PATH
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo
mkdir androidx-main && cd androidx-main
repo init -u https://android.googlesource.com/platform/manifest -b androidx-main --partial-clone --clone-filter=blob:limit=10M
repo sync
```
2. Guides:
https://source.android.com/docs/setup/contribute/submit-patches
https://source.android.com/docs/setup/contribute/life-of-a-patch

If that is cumbersome, we also gladly accept changes only in platform sourceSets.

**Comment by alexzhirkevich** [comment]
Let's have it in uikitMain only for now then? Anyway the amount of people using this modifier for purposes other than text selection is quite low I guess. Having default magnifier for text fields and selection container will close 99% of this modifier usage. Modifier itself can be internal for now, just to implement the default text selection magnifier that I lack a lot.

**Comment by mazunin-v-jb** [comment]
Yes, I think making uikit only implementation of magnifier is a good solution here 👍

**Comment by alexzhirkevich** [comment]
@mazunin-v-jb 
I found some bugs in text selection while implementing magnifier. Reproduces on current jb-main `df6b5e63c69c35c4c18022ef99e017072af4601d`:

https://github.com/JetBrains/compose-multiplatform-core/assets/63979218/47dd5ff4-2ecc-4d51-8339-34afbbd41394

Double tap with hidden keyboard causes menu flashing:

https://github.com/JetBrains/compose-multiplatform-core/assets/63979218/94ad03f9-7943-4829-b3b5-61e05b3d3865

Double tap menu with open keyboard is incorrect. If you then drag this text a little bit, correct menu shows:

https://github.com/JetBrains/compose-multiplatform-core/assets/63979218/04daa0f4-d6f7-4c70-bb71-98435625e788

**Comment by alexzhirkevich** [comment]
Merged with 1.6 beta and moved to uikit-only here: #1000

**Comment by mazunin-v-jb** [comment]
@alexzhirkevich, thank you! I'll take a look 

Upd. I reproduced the first issue, but couldn't reproduce the second one. Could you please [create an issue here](https://github.com/JetBrains/compose-multiplatform/issues/new/choose) with the flashing context menu and tag me in it?

**Comment by alexzhirkevich** [comment]
There is no extra info i can provide actually except that i run mpp app on 12 mini /17.2.1. May be related to the https://github.com/JetBrains/compose-multiplatform-core/pull/964. Or because of ClearFocusBox is used there

**Comment by alexzhirkevich** [comment]
@mazunin-v-jb  Yep, it does not happen on Example1 screen. Seems like ClearFocusBox issue

**Comment by alexzhirkevich** [comment]
Here is ClearFocusBox i use on my project. I replaced your mpp ClearFocusBox with it and no more flashing occurs

```kotlin
@Composable
fun ClearFocusBox(
    modifier: Modifier = Modifier,
    enabled : Boolean = true,
    contentAlignment: Alignment = Alignment.TopStart,
    content : @Composable BoxScope.() -> Unit
) {
    val focusManager = LocalFocusManager.current

    var hasFocus by remember {
        mutableStateOf(false)
    }
    val focusModifier = if (enabled && hasFocus)
        Modifier.pointerInput(0) {
            detectTapGestures {
                focusManager.clearFocus(force = true)
            }
        }.onKeyEvent {
            if (it.key == Key.Escape) {
                focusManager.clearFocus(force = true)
                true
            } else {
                false
            }
        }
    else Modifier

    Box(
        modifier = modifier.onFocusChanged {
            hasFocus = it.hasFocus
        } then focusModifier,
        contentAlignment = contentAlignment,
        content = content
    )
}

```

**Pull request closed without merging**
