### PR TITLE
Remove scene APIs that were deprecated with `ERROR` level since 1.6

### PR DESCRIPTION
**Pull request by MatkovIvan**
No release notes because it wasn't supposed to be really public + deprecated with `ERROR` level for a while

### CODE REVIEW

**Comment by igordmn** [comment]
How much do we need to remove it?

`ComposeScene`, `ImageComposeScene` were stable API's in stable versions.

**Comment by MatkovIvan** [comment]
Basically for it's for cleaning-up purposes. It's deprecated with `ERROR` level for 2 versions, so it fits to the policy

**Review by igordmn — APPROVED** [review]
Needs 2 approves

**Review by m-sasha — APPROVED** [review]

**Comment by MatkovIvan** [comment]
(rebase without changes)

**Pull request merged**
