### PR TITLE
Add `linuxArm64` target

### PR DESCRIPTION
**Pull request by JakeWharton**
Was omitted from #292.

### CODE REVIEW

**Review by dima-avdeev-jb — APPROVED** [review]
Thanks!

**Review by eymar — APPROVED** [review]

**Comment by hfhbd** [comment]
How do you get the linuxArm64 artifact? I don't find it here: https://repo1.maven.org/maven2/org/jetbrains/kotlinx/

**Comment by eymar** [comment]
> How do you get the linuxArm64 artifact? I don't find it here: https://repo1.maven.org/maven2/org/jetbrains/kotlinx/

oops, I didn't check it.

Indeed, there is only x64 builds of coroutines and atomicfu
https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-linuxx64/
https://repo1.maven.org/maven2/org/jetbrains/kotlinx/atomicfu-linuxx64/

So it's probably the reason why it was ommited.

**Comment by JakeWharton** [comment]
Ah, sorry. I could have sworn it was.

Probably have to wait for whatever this is https://github.com/Kotlin/kotlinx-atomicfu/issues/253#issuecomment-1298598854 which was posted to a bunch of issues about target support. Linux ARM is a pretty glaring omission, though, since it's not exactly as esoteric as 32-bit linux or android native that people also request.

**Comment by hfhbd** [comment]
Yeah, strangely only kx serialization publishes linuxArm but without tests.

**Pull request merged**
