### PR TITLE
Update skiko to 0.8.11

### PR DESCRIPTION
**Pull request by eymar**
It's based on skia m126
Skiko update PR: https://github.com/JetBrains/skiko/pull/969

## Testing

- The demo runs on all platforms
- The tests passed

This should be tested by QA

### Highlights - Multiple Platforms
- Skiko version was updated to 0.8.11 (It is based on skia m126 release)

### CODE REVIEW

**Comment by igordmn** [comment]
For the future:
- hotfix version should be reserved only for real hot fix updates. A Skia update should increase either the third, or better the second number.
- if we need a dev build, we need to build `0.8.10+my-build`. Everything after `+` is ignored by Gradle order comparator. but we need to modify Skiko Gradle scripts a little.

**Comment by eymar** [comment]
Compose tests passed

**Review by igordmn — APPROVED** [review]

**Review by MatkovIvan — APPROVED** [review]
It should be mentioned in a changelog (please restore this part of the description template)

**Comment by igordmn** [comment]
> It should be mentioned in a changelog (please restore this part of the description template)

Do we really need it? Nothing is changed for users.

If we decide to keep it, I wouldn't mention it is a Highlight, and don't mention Skiko, only Skia

**Comment by MatkovIvan** [comment]
skia + moving to features block lgtm

**Pull request merged**
