### PR TITLE
Draft of UIKit interop

### PR DESCRIPTION
**Pull request by dima-avdeev-jb**

### CODE REVIEW

**Comment by Tiebe** [comment]
@dima-avdeev-jb No hurry of course, but is this still being worked on? Awesome work though!

**Comment by dima-avdeev-jb** [comment]
> @dima-avdeev-jb No hurry of course, but is this still being worked on? Awesome work though!

Yes, I am still working on it right now.

**Comment by dima-avdeev-jb** [comment]
@Tiebe This PR will be moved to another branch. All this code will be saved.
https://github.com/JetBrains/androidx/tree/dima-avdeev/uikit-interop-3

**Comment by Tiebe** [comment]
> @Tiebe This PR will be moved to another branch. All this code will be saved. https://github.com/JetBrains/androidx/tree/dima-avdeev/uikit-interop-3

Awesome, sounds good!

**Pull request closed without merging**
