### PR TITLE
Modifier.dragAndDropTarget integration WIP

### PR DESCRIPTION
**Pull request by tunjid**
Describe proposed changes and the issue being fixed

WIP for  [Modifier.dragAndDropTarget](https://github.com/JetBrains/compose-multiplatform/issues/4235)

This PR is a skeleton for supporting `Modifier.dragAndDropTarget`.

On Android, I implemented drag and drop in [`AndroidComposeView`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/platform/AndroidComposeView.android.kt;drc=ba39d3f3c4fa7484cb87610cf1d872a14e3b6253;l=268). The platform DragAndDropListener is used to implement the Compose common `DragAndDropManager` interface and is attached directly to the View. Once events come in, the listener forwards them to the root [`Modifier`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/platform/AndroidComposeView.android.kt;drc=ba39d3f3c4fa7484cb87610cf1d872a14e3b6253;l=424) hosted in the [listener](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/platform/AndroidComposeView.android.kt;drc=ba39d3f3c4fa7484cb87610cf1d872a14e3b6253;l=2720).

For Desktop, this can be done directly on the [`contentPane`](https://github.com/tunjid/me/blob/e068b95464d75bf41507418439a48d9012a44287/common/core-ui/src/desktopMain/kotlin/com/tunjid/me/core/ui/dragdrop/SwingRootDragDropNode.kt#L95) in the desktop window as I did a few years back when prototyping the integration. This PR shows the skeleton implementation for that, without actually attaching it to the desktop window.

While this is the most direct and easiest integration point, I'm not sure if it makes the API difficult to implement for other skiko targets. I'm not sure what the threshold is for integrating at the `PlatformContext` level and if I should be looking at that.

Feedback most welcome and next steps appreciated.

## Testing

Describe how you tested your changes. If possible and needed:
- Test it on a sample project
- Write unit tests
- Provide a code snippet

This should be tested by QA

### Section - Subsection
- Describe a change for adding it to https://github.com/JetBrains/compose-multiplatform/blob/master/CHANGELOG.md
- _(prerelease fix)_ Fix some bug that introduced in a prerelease version (dev/beta). It will be included in a dev/beta changelog, but excluded from a stable changelog

### Section - Subsection
- Describe another change if needed

## Google CLA
You need to sign the Google Contributor’s License Agreement at https://cla.developers.google.com/.
This is needed since we synchronise most of the code with Google’s AOSP repository. Signing this agreement allows us to synchronise code from your Pull Requests as well.

### CODE REVIEW

**Comment by tunjid** [comment]
@igordmn Just checking for an update. Is there prerequisite work needed?

**Comment by igordmn** [comment]
Thanks for the PR!

Right now we are looking on how the API should look like for end users. It may be hard to adapt what was designed for Android to other platforms.

Before that we can't be sure what is needed in the implementation.

Overall we have 2 requirements for API:
- it should allow to write platform-independent code on user side.
- it should work for any implementation of Compose that uses `ComposeScene` directly (like [LWJGL](https://github.com/JetBrains/compose-multiplatform/tree/master/experimental/lwjgl-integration)). I.e. any `java.awt` class shouldn't be used inside the implementation. If it is needed, it should be injected via `PlatformContext`.

When we have more understanding on how it should like, we'll return to your PR. If it will be compatible with the API, we can merge or use it as a base. If not, we might implement it from scratch.

cc @m-sasha @elijah-semyonov

**Comment by elijah-semyonov** [comment]
I think that @igordmn response sums it pretty well. We work in different branches for different platforms and will try to converge our solution to a most common denominator in the end. Just merging this PR as it is won't probably make a lot of sense.

**Comment by m-sasha** [comment]
I went ahead and implemented it [here](https://github.com/JetBrains/compose-multiplatform-core/pull/1433)

**Comment by tunjid** [comment]
Closing this as its been implemented. Thanks @m-sasha.

**Pull request closed without merging**
