### PR TITLE
Update skiko to 0.7.87

### LINKED ISSUE #1888: Slashes with text ellipsis overflow behaves differently than Android (Desktop)
When I have got a `Text` with slashes (like a file path) as text that doesn't fit the current screen, in the Android version of compose the string gets cut partially and not the whole word.  The Desktop version cuts the whole word instead until the slash.

**Desktop:** "FooBar" is not shown, just the ellipsis.

Desktop
ellipsis

**Android:** "Foo" is shown + Ellipsis

Android

Code sample:

```
MaterialTheme {
    Text(
        text = "/Path/To/A/Fantastic/Path/Named/FooBar",
        overflow = TextOverflow.Ellipsis,
        fontSize = 23.sp,
        maxLines = 1,
    )
}
```

`TextOverflow.Clip` behaves in equally in both platform by cutting the whole word.

### PR DESCRIPTION
**Pull request by MatkovIvan**
## Proposed Changes

- Update skiko to `0.7.87`

## Issues Fixed

Fixes https://github.com/JetBrains/compose-multiplatform/issues/1888
image

### CODE REVIEW

**Comment by igordmn** [comment]
- as far as I remember we had failed screnshots tests because of the changed antialiasing in the new Skia (at least on Windows, didn't check on macOs)
- we renamed the skiko artifact (I will make a PR later)

**Comment by igordmn** [comment]
> we renamed the skiko artifact (I will make a PR later)

false alert, we made a mistake in [the change](https://github.com/JetBrains/skiko/pull/813), and effectively didn't change anything yet (but we will later)

**Review by igordmn — APPROVED** [review]
I have fixed the screenshots. Now it is safe to merge

**Review by Walingar — APPROVED** [review]

**Comment by Walingar** [comment]
Let's merge and build Compose dev version before merging 1.6.0 Jetpack Compose

**Pull request merged**
