### PR TITLE
Add CfW tests GH workflow

### PR DESCRIPTION
**Pull request by eymar**
Running `./gradlew :mpp:testWeb` in GitHub action

Also:
- fixed a few tests. They don't fail on MacOs but fail on Linux. The failure were caused by different display density and not updated key mappings.

### CODE REVIEW

**Review by Schahen — APPROVED** [review]
Thank you for fixing the density issue!

**Comment by igordmn** [comment]
Why this was added? We aim to move all CI checks to TeamCity, so they work the same during publication and PR checks.

**Comment by eymar** [comment]
> Why this was added? We aim to move all CI checks to TeamCity, so they work the same during publication and PR checks.

The aim of this workflow is to have a temporary alternative for our TC docker based pipeline, which has unexpected issues from time to time. Having this workflow would help us evaluate the "flakiness" of docker based pipeline. (also it gets started sooner - faster feedback). Both (TC and this) pipelines are enabeled. 

cc: @igordmn

**Comment by igordmn** [comment]
Sure, temporary fixes are fine if they are helpful. Though, in the longer term, we should fix TC, speed up the start, and remove GA.

**Pull request merged**
