### PR TITLE
Initial implementation of Lifecycle for Web targets

### PR DESCRIPTION
**Pull request by kropp**
This MR adds initial implementation for Lifecycle events on web targets (primarily Wasm).

I'm not sure it is possible to handle STOP/DESTROY events on Web, please correct me if I'm wrong.

### CODE REVIEW

**Review by Schahen — COMMENTED** [review]
Looks good to me. One thing that still worth to discuss in future whether we indeed want to treat the focusout as pause but this is irrelevant to the purpose of this PR which is - to introduce the very concept of Lifecycle to the wasm target

**Review by Schahen — APPROVED** [review]
Looks good to me. One thing that still worth to discuss in future whether we indeed want to treat the focusout as pause but this is irrelevant to the purpose of this PR which is - to introduce the very concept of Lifecycle to the wasm target

**Review by MatkovIvan — APPROVED** [review]
Let's not squash change in mpp and adding web support to one commit

**Comment by MatkovIvan** [comment]
cherry-picked 1433d2d0f6ee137bb00bc79361c81c8ebe2c54c5 from this branch. let's do changes in mpp demo later. Closing this PR

**Pull request closed without merging**
