### PR TITLE
Feat: Add onClick parameter for Tray

### LINKED ISSUE #290: onClick handlers for tray icon
Currently, it's only possible to attach a menu to the tray icon. For small helper applications, it would be nice to also have access to an onClick event on the icon directly, without having to go through a single-entry menu. Examples of applications that work like this are 1Password, JetBrains Toolbox, [Coca](https://apps.apple.com/de/app/coca/id1000808993?mt=12) and others.

### PR DESCRIPTION
**Pull request by rin0chan**
## Issues Fixed

Fixes: https://github.com/JetBrains/compose-multiplatform/issues/290

This is a simple implementation. 

Additionally, I noticed a comment in `Tray.desktop.kt`:

```
// TODO(demin): add mouse click/double-click/right click listeners (can we use PointerInputEvent?). 
```

I also think it would be better to use `PointerInputEvent` to handle click events, but it seems like the functionality of Tray is fully implemented using AWT, and I'm not sure how to handle it. 🤔

I have written an example for the modified code in 

`compose/desktop/desktop/samples/src/jvmMain/kotlin/androidx/compose/desktop/examples/tray/Tray.kt`

### CODE REVIEW

**Comment by Walingar** [comment]
Thank you for your submission and contribution to Compose Multiplatform!

Please, sign the Google Contributor’s License Agreement at https://cla.developers.google.com/. 
This is needed since we synchronise most of the code with Google’s [AOSP](https://android.googlesource.com/platform/frameworks/support/+/androidx-main) repository. Signing this agreement allows us to synchronise code from your Pull Requests as well.

**Comment by rin0chan** [comment]
Yes, I have signed one.

Screenshot_20230421-185257_Chrome~2

**Comment by eymar** [comment]
Hi @whitescent !
I'm running the example you provided on macOS. And for me onClick is never invoked.

What OS did you use to test it? I'm wondering if its behaviour is somehow related to OS.

**Comment by rin0chan** [comment]
> Hi @whitescent ! I'm running the example you provided on macOS. And for me onClick is never invoked.
> 
> What OS did you use to test it? I'm wondering if its behaviour is somehow related to OS.

I'm testing my code using Windows, and I think that macOS may not use `MouseEvent.BUTTON1` to detect a mouse click 🤔.

I don't have a machine running macOS on my hands, so I can't test this. I'm sorry

**Comment by eymar** [comment]
Thanks! 
I tested on Ubuntu too. Clicking on the yellow tray icon doesn't print anything here too. 
It even shows the tray icon weirdly comparing to Toolbox app (in the tray, to the left from language).
The tray icon of this example is in the left corner, but not in a tray.

Screenshot from 2023-04-21 16-40-43



We'll need to discuss the Tray API within the team. Ideally it should work in all OS properly.

**Pull request closed without merging**
