### PR TITLE
Initial iOS floating cursor support

### LINKED ISSUE #4593: iOS 17 hidden trackpad doesn't work in the TextFields (hold space bar and swipe to move cursor)
**Describe the bug**
The iOS 17 introduced hidden trackpad feature, when you can hold the spacebar and then move the cursor with the swipe on the keyboard. 
This doesn't move the cursor in any TextField in Jetpack Compose Multiplatform.
Surprisingly - the same feature works fine on Android with the same code.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): 17.2
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): any iOS device or simulator

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
1. Add a simple text field to the multiplatform app:
```Kotlin
@Composable
fun App() {
    MaterialTheme {
        var text by remember { mutableStateOf("") }
        TextField(
            modifier = Modifier.fillMaxWidth(),
            value = text,
            onValueChange = { text = it }
        )
    }
}
```
2. Run the app on either iOS 17 device or iOS 17 simulator
3. Enter something in the text field
4. Hold the space bar on the soft keyboard and move finger while holding it

**Expected behavior**
Cursor should move in the direction finger moves. Actually - cursor stays in place.

**Screenshots**
iOS simulator, how it actually works:
https://github.com/JetBrains/compose-multiplatform/assets/6439273/de8baba4-0785-4bb8-905e-6cbb34f58957

The same app running on Android Emulator (API 34):
https://github.com/JetBrains/compose-multiplatform/assets/6439273/57c61cc2-2aa7-44c3-a4c1-3778b0a4c693

**Additional context**
This is the new feature in iOS 17 - https://www.cnet.com/tech/mobile/this-secret-ios-trackpad-makes-typing-on-your-iphone-so-much-easier/

### PR DESCRIPTION
**Pull request by alexzhirkevich**
## Proposed Changes

Initial iOS floating cursor support.

https://github.com/JetBrains/compose-multiplatform-core/assets/63979218/1c6681dc-5295-4712-80e0-f08f58f4687e

## Testing

Test: hold space bar and move the cursor

## Issues Fixed

Fixes: https://github.com/JetBrains/compose-multiplatform/issues/4593

### CODE REVIEW

**Comment by ASalavei** [comment]
Many thanks for another feature!
LGTM, however I want to do some tests, it will take a day or two.

**Comment by alexzhirkevich** [comment]
> Many thanks for another feature! LGTM, however I want to do some tests, it will take a day or two.

Sure thing. Please test how it works on older iOS versions if you can. Not sure why the issue author decided that it was added in the iOS 17, I believe it has been available for a long long time

**Review by ASalavei — APPROVED** [review]
LGTM. Tests passed. Sorry for the delay.
cc @elijah-semyonov @mazunin-v-jb

**Review by mazunin-v-jb — APPROVED** [review]
@alexzhirkevich, thanks for contribution!
and sorry for huge delay
LGTM too

**Pull request merged**
