### PR TITLE
allow to specify size of surface and take screenshot within ComposeUiTest

### PR DESCRIPTION
**Pull request by ialokim**
## Proposed Changes

Currently, screenshots can be taken using `ImageComposeScene`. However, using this approach it is not possible to interact with the UI in an automated way before taking the screenshots. On the other hand, Interaction with UI nodes is possible in testing environment (using `runComposeUiTest()`), but it uses a hard-coded size for the scene and the skia surface is not exposed to the user as it is marked as `private`.

This PR proposes to:
  - allow the user to specify custom width and height for the compose scene used during the test, by calling `runDesktopComposeUiTest(width, height)` (this mirrors the behavior on Android where you can pass custom activities using `runAndroidComposeUiTest(activityClass)`)
  - add a function to take a screenshot of the current Compose scene

## Testing

Test: Unfortunately I could not test the changes since I was unable to get the huge repository to compile using IntelliJ (any hints are very appreciated), but I did test the same functionality before using this kind of code:

```kotlin
// needs to use hard-coded size of image to work as expected (to match hard-coded size inside [ComposeUITest.desktop])
private val surface = Surface.makeRasterN32Premul(1024, 768)

@OptIn(InternalTestApi::class)
private fun DesktopComposeTestRule.takeScreenshot(): Image {
    surface.canvas.clear(Color.TRANSPARENT)
    scene.render(surface.canvas, mainClock.currentTime)
    return surface.makeImageSnapshot()
}
```

---

CLA is signed

### CODE REVIEW

**Comment by ialokim** [comment]
related to https://github.com/JetBrains/androidx/commit/11e2362248228175547e29fa37fd58459120f685

**Comment by igordmn** [comment]
Thanks! I will check it soon. Not sure if it will be in 1.2.0, but it can be in the next versions (1.2.1, 1.3.0)

Could you sign [CLA](https://cla.developers.google.com/clas) and add
"CLA is signed" to the commit info?

We usually upstream changes from this fork to https://github.com/androidx/androidx, and it requires that the contributor is signed CLA.

Also, do you agree that the author field can be lost in the future? We'll try to keep it, but usually during upstreaming or rebasing on the latest JetPack Compose, we have to merge some commits.

**Comment by ialokim** [comment]
I've signed the CLA, rebased on current `jb-main` and added "CLA is signed" to the commit message.

It'd be acceptable for me if the author information was lost.

Looking forward to having this added to compose, hopefully already in the next release :)

**Comment by igordmn** [comment]
> and added "CLA is signed" to the commit message.

Thanks! Could you add it into the PR message too? It will be squashed into one commit with the message from the PR.

Code looks good to me. Also I refactored your code in the branch, could you check it?

https://github.com/JetBrains/androidx/pull/310/commits/6f1a7f62bdfa611d6d88daba8f2854fa2f75bde4

**Comment by ialokim** [comment]
> Code looks good to me. Also I refactored your code in the branch, could you check it?

Just had a look at it and your changes look all sensible to me! Thanks for picking this up so quickly!

**Comment by igordmn** [comment]
>  Could you add it into the PR message too? It will be squashed into one commit with the message from the PR.

A reminder :)

**Comment by igordmn** [comment]
@dima-avdeev-jb, could you look at the PR too?

**Comment by ialokim** [comment]
> > Could you add it into the PR message too? It will be squashed into one commit with the message from the PR.
> 
> A reminder :)

Sorry, just added it :)

**Review by igordmn — APPROVED** [review]

**Comment by dima-avdeev-jb** [comment]
@ialokim @igordmn 
Made unit test in this PR: https://github.com/ialokim/androidx/pull/1

**Review by dima-avdeev-jb — APPROVED** [review]

**Comment by ialokim** [comment]
Amazing to have this merged, thank you! :tada: 

Btw, do you have any documentation on how to properly set up the environment (IntelliJ) for building Compose from sources (preferably ignoring all the other packages in androidx)? I couldn't find any and just opening/importing to IntelliJ didn't work for me.

**Comment by igordmn** [comment]
We have it [here](https://github.com/JetBrains/compose-jb/tree/master/compose). There still can be issues though.

**Comment by ialokim** [comment]
I was able to setup and build the (desktop) project following the instructions, worked like a charm!

**Pull request merged**
