### PR TITLE
Remove unused code in settings.gradle

### PR DESCRIPTION
**Pull request by igordmn**
- remove non-COMPOSE modules
- remove TODO and commented code
- remove Gradle Enterprise plugin. It seems only work in internal Google environment. We may consider similar optimization in the future

In this PR I don't try to avoid merge-conflicts with new Jetpack Compose's. It is better to maintain the list of modules ourselves. If new modules are added, there will be a merge conflict, and we will see what is new, and can do conscience porting/testing of the new modules.

### CODE REVIEW

**Comment by Walingar** [comment]
Please, rebase branch on up-to-date master, since new changes appeared there

**Comment by igordmn** [comment]
>Please, rebase branch on up-to-date master, since new changes appeared there

Done.

Also, it seems the native build failed, investigating

**Comment by igordmn** [comment]
Can't reproduce locally. Will try to return some code

**Comment by igordmn** [comment]
> Can't reproduce locally. Will try to return some code

The first fix returning `placeholder` magically helped :)

**Comment by Walingar** [comment]
@igordmn yes, placeholder should be kept, this is workaround for something :)

**Review by Walingar — APPROVED** [review]

**Pull request merged**
