### PR TITLE
Fix compilation in NativeFont

### PR DESCRIPTION
**Pull request by Walingar**
## Proposed Changes

  - add else for when statement, since when should be exhaustive

## Testing

Test: compile ios part

## Issues Fixed

No issues related to the PR

### CODE REVIEW

**Comment by Walingar** [comment]
See error here: [build](https://teamcity.jetbrains.com/buildConfiguration/JetBrainsPublicProjects_Compose_3_Subtasks_1ComposePublishExtendedIconsUikit/4132334?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&hideTestsFromDependencies=false)

**Review by MatkovIvan — CHANGES_REQUESTED** [review]
> 'when' expression must be exhaustive, add necessary 'else' branch

I guess it's supposed to be exhaustive. `PlatformFont` is declared as `sealed`

> Sealed classes and interfaces represent restricted class hierarchies that provide more control over inheritance. All direct subclasses of a sealed class are known at compile time. No other subclasses may appear outside the module and package within which the sealed class is defined.

**Comment by Walingar** [comment]
@MatkovIvan sure, but it fails to compile. When we provide else it writes that it is redundant

**Review by MatkovIvan — COMMENTED** [review]
Let's make sure that it's tracked as compiler bug and add `ignore` + TODO with link to YT

**Review by MatkovIvan — APPROVED** [review]

**Pull request merged**
