### PR TITLE
Jetpack Compose 1.5.0-beta03

### PR DESCRIPTION
**Pull request by igordmn**
- this PR will be pushed directly to jb-main

### CODE REVIEW

**Comment by Walingar** [comment]
It's difficult to point comments on files in this PR :) . So, FocusedBounds.kt:71 -- 
```
fun interface InvokeOnLayoutCoordinates {
    fun invoke(focusedBounds: LayoutCoordinates?)
}
```

Is introduced in foundation, shouldn't we mark it as internal API, not to expose it in common?

**Comment by Walingar** [comment]
I briefly checked the PR. Everything except comment above looks good to me. Also, most of the commits were reviewed and tests work fine, so let's discuss `InvokeOnLayoutCoordinates` and merge

**Comment by igordmn** [comment]
> Is introduced in foundation, shouldn't we mark it as internal API, not to expose it in common?

It was introduced in 1.4, I just returned it after the merge [here](https://github.com/JetBrains/compose-multiplatform-core/pull/663)

Probably we can make it `private`, if it was a mistake (better in a separate PR to jb-main). @eymar, what do you think?

**Review by Walingar — APPROVED** [review]

**Comment by eymar** [comment]
It was added even before 1.4.
But there's no need for it to be public. It was initially made public by a mistake I guess. 
Let's make it internal. It's a breaking change though. But I assume it's safe to do, since no one would need to use it directly outside of compose repo. And since we publish beta first, we'll hear some feedback if something is wrong.

**Comment by igordmn** [comment]
We have this policiy regarding such API's:
> If the API is not documented, accidentally made public, doesn't make sense as a public API, and isn't used by anyone, we can mark it as internal straight away, but consult that with the author of the API.

I made a separate PR: https://github.com/JetBrains/compose-multiplatform-core/pull/690

**Pull request merged**
