### PR TITLE
StringFormatTests on skikoTest

### PR DESCRIPTION
**Pull request by dima-avdeev-jb**
## Proposed Changes

  - Added tests to functions String.format() after addition with calendar in PR https://github.com/JetBrains/compose-multiplatform-core/pull/717

## Testing

Run tests:
`./gradlew :mpp:testDesktop`
`./gradlew :mpp:testUIKit`

### CODE REVIEW

**Comment by dima-avdeev-jb** [comment]
@alexzhirkevich Added tests to your changes

**Comment by alexzhirkevich** [comment]
Thanks, it's a good point. I shoul've include such tests in my PR. 
Or maybe it shoul've been tested before so i didn't have to fix obvious bugs in it :D

**Review by eymar — APPROVED** [review]

**Comment by alexzhirkevich** [comment]
Probably `not_enough_args` should also be tested? And this case should thow a `MissingFormatArgumentException` like on JVM? 

Or does it matter to the internal function?

**Comment by dima-avdeev-jb** [comment]
@alexzhirkevich I tryed to write test:
```Kotlin
fun not_enough_args() {
        val result = "str %1\$".format()
    }
```

But exception not occurs.
Result is 'str %1$'

**Review by MatkovIvan — APPROVED** [review]

**Comment by alexzhirkevich** [comment]
I know. I mean it is inconsistent with jvm. Jvm (Android actual) format will throw an exception

**Comment by dima-avdeev-jb** [comment]
> I know. I mean it is inconsistent with jvm. Jvm (Android actual) format will throw an exception

Ok. because it is internal function we can stay it as is now.

**Pull request merged**
