### PR TITLE
[Post-upstream] Add the lineHeight parameter to SelectionHandle

### PR DESCRIPTION
**Pull request by ASalavei**
Post-upstreaming CL: https://android-review.googlesource.com/c/platform/frameworks/support/+/3316900

### CODE REVIEW

**Comment by igordmn** [comment]
Is it a cherry-pick?

If so, you need it to push it to `jb-main` without a PR squashing.

A PR may be useful if you think you need to run CI or think that it needs review or approving of cherry-pick

**Comment by igordmn** [comment]
> Is it a cherry-pick?

Did you cherry-pick https://github.com/androidx/androidx/commit/587acc03a43079a25b8ed147acbd83a66039a01e?

I see that commit message is not the same, and I am not sure about the content. We should avoid changing the commits after cherry-picking.

**Comment by igordmn** [comment]
> We should avoid changing the commits after cherry-picking.

It is useful during merges and comparing releases, as git has tools to identify cherry picks (`git cherry`, not sure how it works). It is also useful to see the source of the changes.

If it contain conflicts, and require additional changes, then we: make a PR, add the changes, check CI, then after its green - merge a PR branch and push to jb-main manually, keeping the original cherry-pick commit. Additionally: if changes aren't mechanical, add a reviewer.

**Comment by ASalavei** [comment]
@igordmn , sorry, still getting in to the upstreaming.

> Did you cherry-pick https://github.com/androidx/androidx/commit/587acc03a43079a25b8ed147acbd83a66039a01e?

Yes, but it had conflicts. I simplified commit message keeping the same title - my bad.

> If it contain conflicts, and require additional changes, then we: make a PR, add the changes, check CI, then after its green - merge a PR branch and push to jb-main manually, keeping the original cherry-pick commit. Additionally: if changes aren't mechanical, add a reviewer.

Yep, I tried to make something close to it... except full commit message.

**Pull request merged**
