### PR TITLE
Don't call UITextInputDelegate methods from UITextInputService on user input on iOS

### LINKED ISSUE #3101: Korean characters are not normally entered in the TextField of iOS.
**Describe the bug**
Korean characters are not normally entered in the TextField of iOS.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): 16.4
- OS architecture (x86 or arm64): arm64

**To Reproduce**

source code
```kotlin
   MaterialTheme {
        Column {
            Text("OS: ${getPlatformName()}")
            Text("typing sequence : ㄱ, ㅏ, ㅇ, ㄴ, ㅏ, ㅁ, ㅇ, ㅕ, ㄱ")
            Text("Expected result : 강남역")
            var text by remember { mutableStateOf(TextFieldValue()) }
            TextField(text, onValueChange = { text = it })
        }
    }
``` 
Type on the keyboard in the order of ㄱ, ㅏ, ㅇ, ㄴ, ㅏ, ㅁ, ㅇ, ㅕ, ㄱ in Korean

**Expected behavior**
"강남역" should be displayed in the TextField.

**Screenshots**

https://user-images.githubusercontent.com/131699670/234071529-09d5d574-b7a4-4d7d-8111-1b092234273d.mp4

### PR DESCRIPTION
**Pull request by paxbun**
## Proposed Changes

  - Added `UITextInputService._tempCurrentInputSession`, which tracks the changes of the current input.
  - Made `UITextInputService` apply the same changes to `_tempCurrentInputSession` that are applied to the current input.
  - Made `UITextInputService.updateState` use `_tempCurrentInputSession` instead of `oldValue`, so `updateState` doesn't call `UITextInputDelegate` methods when the `updateState` is invoked by the user input. This is to correctly handle multi-stage input methods that depend on text selection, such as the Korean input method.

## Testing

Test: Tested using the [Android & iOS template](https://github.com/Jetbrains/compose-multiplatform-ios-android-template) with the following configuration and the following procedure. `App.kt` is modified as the code at the bottom.

### Configurations

* (Physical device) iPad Pro, 11-inch (3rd generation) (iOS 16.5.1) with the system keyboard
* (Physical device) iPad Pro, 11-inch (3rd generation) (iOS 16.5.1) with Magic Keyboard via Bluetooth
* (Physical device) iPad Pro, 11-inch (3rd generation) (iOS 16.5.1) with Magic Keyboard via [Universal Control](https://support.apple.com/en-us/HT212757)
* (Simulator) iPhone 14 (iOS 16.4) with the system keyboard
* (Simulator) iPhone 14 (iOS 16.4) with a hardware keyboard
* (Simulator) iPad Pro, 12.9-inch (5th generation) (iOS 16.0) with the system keyboard
* (Simulator) iPad Pro, 12.9-inch (5th generation) (iOS 16.0) with a hardware keyboard

### Procedure

0. Install the Korean 2-set input method. The keyboard layout and the keys to be used are as follows.

image

1. Press the button.
2. Type "ㅋㅓㅁㅍㅗㅈㅡ" in 5 seconds (as shown in the image above), which must be combined as "컴포즈".
    > Compose is 컴포즈 in Korean.
3. Wait until "hello" is appended to the text field.
    > This is to ensure that the value is updated correctly when the text field has the focus.
4. Select all text and press the backspace key. All text must be removed.
    > This is to ensure that the selection is updated correctly.

5. Press the button.
6. Type "ㅋㅓㅁㅍㅗㅈㅡ" in 5 seconds.
7. Wait until "hello" is appended to the text field.
8. Select all text and copy and paste it.
    > This also is to ensure that the selection is updated correctly.

## Issues Fixed

Fixes: JetBrains/compose-multiplatform#3101

## Test Code

```kotlin
@Composable
fun App() {
    val coroutineScope = rememberCoroutineScope()
    MaterialTheme {
        Column {
            Text("OS: ${getPlatformName()}")
            var text by remember { mutableStateOf("") }
            var currentCounter by remember { mutableStateOf("") }
            Row {
                TextField(text, onValueChange = { text = it })
                Spacer(Modifier.width(5.dp))
                Text(currentCounter)
            }
            var adding by remember { mutableStateOf(false) }
            Button(
                onClick = {
                    coroutineScope.launch {
                        try {
                            adding = true
                            for (i in (1..5).reversed()) {
                                currentCounter = i.toString()
                                delay(1.seconds)
                            }
                            currentCounter = ""
                            text += "hello"
                        } finally {
                            adding = false
                        }
                    }
                },
                enabled = !adding,
            ) {
                Text("Add \"hello\" after 5 seconds")
            }
        }
    }
}
```

## Test Results

<details>
<summary>Before the fix (1.4.1 with Kotlin 1.8.20)</summary>

* (Physical device) iPad Pro, 11-inch (3rd generation) (iOS 16.5.1) with the system keyboard

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/019a956f-98a6-4eed-89c4-c128bf546106

* (Physical device) iPad Pro, 11-inch (3rd generation) (iOS 16.5.1) with Magic Keyboard via Bluetooth

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/ecb2c953-cdb2-40f2-9804-afcfb8c73070

* (Physical device) iPad Pro, 11-inch (3rd generation) (iOS 16.5.1) with Magic Keyboard via Universal Control

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/a0312311-9115-4626-95e3-a9f5a1c578a2

* (Simulator) iPhone 14 (iOS 16.4) with the system keyboard

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/0b6eaf4d-a108-49cf-9265-5dd140a43e68

* (Simulator) iPhone 14 (iOS 16.4) with a hardware keyboard

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/466f0f78-80b3-4694-9a09-fb2d9b909e0a

* (Simulator) iPad Pro, 12.9-inch (5th generation) (iOS 16.0) with the system keyboard

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/45c77956-7b5a-42ef-8ba4-bbf908df94d3

* (Simulator) iPad Pro, 12.9-inch (5th generation) (iOS 16.0) with a hardware keyboard

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/ecd40420-0646-4b88-a074-6b478e8a2671

</details>

<details>
<summary>After the fix</summary>

* (Physical device) iPad Pro, 11-inch (3rd generation) (iOS 16.5.1) with the system keyboard

   https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/87387b7f-db69-41d9-bb44-a2290c32d064

* (Physical device) iPad Pro, 11-inch (3rd generation) (iOS 16.5.1) with Magic Keyboard via Bluetooth

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/d2be4887-645f-48fc-a869-3382100bc341

* (Physical device) iPad Pro, 11-inch (3rd generation) (iOS 16.5.1) with Magic Keyboard via Universal Control

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/d839675f-3337-419f-8a26-0585112b4dce

* (Simulator) iPhone 14 (iOS 16.4) with the system keyboard

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/54b2c9eb-9ce2-47c2-949e-ec593ecd55f7

* (Simulator) iPhone 14 (iOS 16.4) with a hardware keyboard

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/74fbb937-b143-44c6-b2f2-8f85ab6e8b30

* (Simulator) iPad Pro, 12.9-inch (5th generation) (iOS 16.0) with the system keyboard

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/4e80865a-47e0-4be9-8c97-26b4d8b28fdf

* (Simulator) iPad Pro, 12.9-inch (5th generation) (iOS 16.0) with a hardware keyboard

  https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/8a92ca1c-601a-4673-bb60-42a82d5b7b95

</details>

### CODE REVIEW

**Comment by paxbun** [comment]
I read [Lower Level Text-Handling Technologies](https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/LowerLevelText-HandlingTechnologies/LowerLevelText-HandlingTechnologies.html) from the Apple Documentation Archive, ran the  [official example](https://developer.apple.com/library/archive/samplecode/SimpleTextInput/Introduction/Intro.html#//apple_ref/doc/uid/DTS40010633), and compared method calls of APLEditableCoreTextView of the example and SkikoUIView.

The two differences between APLEditableCoreTextView and SkikoUIView are:

1. While `APLEditableCoreTextView.positionFromPosition:offset:` returns null when the offset is out of range, `SkikoUIView.positionFromPosition:offset:` returns the coerced position. Changing [`SkikoUIView.positionFromPosition`](https://github.com/JetBrains/skiko/blob/a662a7916568dfdab8f1eddfe56fd7af14ed1864/skiko/src/iosMain/kotlin/org/jetbrains/skiko/SkikoUIView.kt#L384-L392) like the following was not helpful, though.

    ```kotlin
    override fun positionFromPosition(position: UITextPosition, offset: NSInteger): UITextPosition? {
        val p = (position as? IntermediateTextPosition)?.position ?: return null
        val endOfDocument = skiaLayer?.skikoView?.input?.endOfDocument() ?: return null
        val newPosition = p + offset
        return if (newPosition in 0..endOfDocument) {
            IntermediateTextPosition(newPosition)
        } else {
            null
        }
    }
   ```

2. For some reason, UIKit calls `positionFromPosition:beginningOfDocument offset:-300` and `positionFromPosition:endOfDocument offset:300` when the view has gained the focus. While this happens only twice at the very beginning for APLEditableCoreTextView while typing, for SkikoUIView, this happens with every single keystroke. I thought that some logic was resetting the state of SkikoUIView, and I found that the four methods were the culprit. Commenting out the calls to these methods makes the Hangul syllables combine correctly. Here's the full log of my experiments:

    * [APLEditableCoreTextView with "가방"](https://github.com/JetBrains/compose-multiplatform-core/files/12212710/swift.txt)
    * [SkikoUIView with "받침"](https://github.com/JetBrains/compose-multiplatform-core/files/12212713/kotlin.txt)

**Comment by paxbun** [comment]
Additional note: this fix does not affect multi-stage input methods that depend on text marking (i.e., `setMarktedText` and `unmarkText`), such as Chinese or Japanese. Here are my test results:

With "你好世界 (ni hao shijie)":

https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/876169e5-609b-4bc4-8acc-b7c69e6dced0

With "ハロー・ワールド (haro- wa-rudo)":

https://github.com/JetBrains/compose-multiplatform-core/assets/17005454/f4e40bc6-eaed-44d5-9835-09b51a966877

**Comment by dima-avdeev-jb** [comment]
Thanks! We need some time to review it.


But, first can you please sign the Google Contributor’s License Agreement at https://cla.developers.google.com/.
This is needed since we synchronise most of the code with Google’s [AOSP](https://android.googlesource.com/platform/frameworks/support/+/androidx-main) repository. Signing this agreement allows us to synchronise code from your Pull Requests as well.

As a referece, you can look at screenshots in this PR: https://github.com/JetBrains/compose-multiplatform-core/pull/699

And can you please post a screenshot of the signed agreement here as a comment?

**Comment by paxbun** [comment]
@dima-avdeev-jb Here it is:
image

By the way, #699 is opened by me; how about adding the screenshot section to the PR template?

**Comment by dima-avdeev-jb** [comment]
Thanks a lot! Very usefull PR. I will review it soon.

>  how about adding the screenshot section to the PR template?

Good suggestion!

**Review by dima-avdeev-jb — APPROVED** [review]
Thanks! Checked with other languages as well.

**Pull request merged**
